queue_rules:
  - name: default
    conditions:
      - status-success=build

pull_request_rules:
  - name: Automatically merge on CI success and review
    conditions:
      - base=master
      - status-success=build
      - "label=ready to merge"
      - "approved-reviews-by=@oss-approvers"
    actions:
      queue:
        method: squash
        name: default
      label:
        add: ["auto merged"]
  - name: Automatically merge release branch changes on CI success and release manager review
    conditions:
      - base~=^release-
      - status-success=build
      - "label=ready to merge"
      - "approved-reviews-by=@release-managers"
    actions:
      queue:
        method: squash
        name: default
      label:
        add: ["auto merged"]
  - name: Automatically merge PRs from maintainers on CI success and review
    conditions:
      - base=master
      - status-success=build
      - "label=ready to merge"
      - "author=@oss-approvers"
    actions:
      queue:
        method: squash
        name: default
      label:
        add: ["auto merged"]
  - name: Automatically merge autobump PRs on CI success
    conditions:
      - base~=^(master|release-)
      - status-success=build
      - "label~=autobump-*"
      - "author:spinnakerbot"
    actions:
      queue:
        method: squash
        name: default
      label:
        add: ["auto merged"]
  - name: Request reviews for autobump PRs on CI failure
    conditions:
      - base~=^(master|release-)
      - status-failure=build
      - "label~=autobump-*"
      - base=master
    actions:
      request_reviews:
        teams: ["oss-approvers"]
