language: java
jdk:
- oraclejdk8
dist: xenial
sudo: false
install: true
script: gradle/buildViaTravis.sh
before_cache: gradle/prepCaches.sh
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
    secure: cItdRaPMbpiAAnnz1mcnkxZMLZuktDp0aOBGmkxiOHhbDR0vIV7461eCQFebu+7E6/DCtlKsXLrKOPEMLywadIv1YaH1cVZ+ulb0FHI71IcOhi0E9YQn1lDSWnhsX7WFTDd+LTZZuhb1st0a1P0CO+8N1KraXWBb84w+FbbkfbvircRxKAcoNAWuK2kkv4RPRQEtPTmg5eLxYHOf9ywS2CzGni+RJ56WlXuWN69tp2FoXBSZPPhT2KSDIVJRSpntbS+GFi5x7ZaQ25h78nCav7rBagZvYZR1i6+BZzI+sgNYcu5RQF+LiX5FWGW87/rIL+UXmfF1mx4myPXy6fkqm3FXfVb8pxOSXHoB99uZH6xNeEoYvYR00LL9DjilMP5tlF+Q3Fv53Be52OYH9pBsb0YlOpom1yFZxRF6UR/rkrzZdc8djEAwwZD7mQMGTI3IL8zsYfHjkjY+0bNq71uoZXupQIVEng+pBB2NUuV+iDb009wdv0aDKhczojNQeO9b8aU9ACCsdd7OJyElZnTbC4/HvLoTkCZU+1JjEor5GG/zrSEd2wQCeJIewQfjD9rRQxv5V1hhXSF0cKDSoTdR4K2t9x6EM/0uhBgRCtzeOb523d4Jfcjfl3o7cJ1af8jz10fwU1qos4m5PnYI+HRjZ/zdtWxNLFVGzC7UfZ5FAZg=
    secure: DzsUSlkfghCe13AvDtb02a+9blLNYJYR33hQJgMFsxDG/6zovi7OpAgiB9ec10MthC6m5awdckXPmmEprE4UjI00hCPIH+S+62vVF/+1Km37WyUoREASLSFoxbB14Lhu1DBn04Rz5qkmCd5pnoWlo74QlKcOaMcQTFNSmfUBsgG+xid148/AjG8zoq+02JwH21B0uCZd9W2HgAg9OITrPhx3MWcKJj3MO3vX+MqrEO+22nQZZctE7U942MdLCY6CO/JcYKoWMBxyNXTXvxQpOAP7o1twt9SWjSWEz4M+tCRxECjqsDKDU7Nd7XfUgRlxOP/6qWsp/QCZPlFtZiCLfum2VsCKEN8IAc1y82NDX00JwtzjUTf2Aqu0m9gU3YBYwxdAeaWTn7/g6i7TpNSLKSDRf9aSUCYPC0+RZZP0fta4/a8Ca7fxuBL9GpPzn+X583Gliwv1oEIXSCxY5gEeyJCpEZWI5VP/XovEppJcuGhd0+jQ1mquLlzVuu6YZ/nqQqrtLV0a/GkzduP1CK+gtbI4N+MD2VDEQJWPp0OzzptY9Resu4LVJ5yBXB1/tH9L2CltLW4xgymgJiHsHXgiU6fPy+VfdKbdfWmaHvaJjSkgYxPz0dpODFBVhdcEVYQ1szPmXuGJSm8cAIMNzP30aqDhO4VKnwgNYRQW6fmb5lo=
