FROM alpine:3.11
LABEL maintainer="sig-platform@spinnaker.io"
COPY kayenta-web/build/install/kayenta /opt/kayenta
RUN apk --no-cache add --update bash openjdk11-jre
RUN addgroup -S -g 10111 spinnaker
RUN adduser -S -G spinnaker -u 10111 spinnaker
RUN mkdir -p /opt/kayenta/plugins && chown -R spinnaker:nogroup /opt/kayenta/plugins
USER spinnaker
CMD ["/opt/kayenta/bin/kayenta"]
