server:
  port: 8090

kayenta:
  redis:
    enabled: true
  gcs:
    enabled: false
  google:
    enabled: false
#    accounts:
#      - name:
#        project:
#        jsonPath:
#        supportedTypes:
#          - METRICS_STORE
  stackdriver:
    enabled: false

swagger:
  enabled: true
  title: Spinnaker Kayenta API
  description:
  contact:
  patterns:
    - /credentials.*
    - /fetch.*
