redis:
  connection: redis://localhost:${redis.port}

kayenta:

  signalfx:
    enabled: true
    accounts:
    - name: sfx-integration-test-account
      accessToken: ${kayenta.signalfx.apiKey}
      supportedTypes:
      - METRICS_STORE
      defaultScopeKey: canary-scope
      defaultLocationKey: location

  memory:
    enabled: true
    accounts:
    - name: in-memory-store
      supportedTypes:
      - OBJECT_STORE

  configbin:
    enabled: false

  standaloneCanaryAnalysis.enabled: true

keiko:
  queue:
    redis:
      queueName: kayenta.keiko.queue
      deadLetterQueueName: kayenta.keiko.queue.deadLetters

spectator:
  applicationName: ${spring.application.name}
  webEndpoint:
    enabled: true
