name: PR Build

on: [ pull_request ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx2g -Xms2g
  GRADLE_ARGS: -x :kayenta-integration-tests:test
jobs:
  build:
    runs-on: ubuntu-latest
    needs: [integration-tests, provider-integration-tests]
    steps:
    - uses: actions/checkout@v2
    - name: Gradle validation step
      uses: gradle/wrapper-validation-action@v1
    - uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build and Functional tests
      run: ./gradlew build $GRADLE_ARGS

  integration-tests:
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx2g -Xms2g
    name: Integration-tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tests:
          ['Management', 'Swagger']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Gradle validation step
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run Integration Test
        run: |
          ./gradlew kayenta-integration-tests:test --tests ${{ matrix.tests }}Test

  provider-integration-tests:
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx2g -Xms2g
    name: Provider-Integration-tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        provider: ['Prometheus', 'Graphite']
        test: ['canaryAnalysisIsSuccessful', 'canaryAnalysisIsFailed']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Gradle validation step
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run Provider Integration Test
        run: |
          ./gradlew kayenta-integration-tests:test --tests ${{ matrix.provider }}StandaloneCanaryAnalysisTest.${{ matrix.test }}
