name: PR Build

on: [ pull_request ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx2g -Xms2g

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Install Java 8 for cross-compilation support. Setting it up before
    # Java 11 means it comes later in $PATH (because of how setup-java works)
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/cache@v1
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Build
      run: ./gradlew -PenableCrossCompilerPlugin=true build
